export const translations = {
  es: {
    appTitle: 'Amazon Fleet Damage Tracker',
    fleet: 'Flota',
    damages: 'Daños',
    totalVans: 'Total de Vans',
    activeDamages: 'Daños Activos',
    addVan: 'Agregar Van',
    reportDamage: 'Reportar Daño',
    vanNumber: 'Número de Van',
    vanType: 'Tipo de Van',
    vin: 'VIN',
    plate: 'Placa',
    registrationExp: 'Expiración Registro',
    assetStatus: 'Estado del Activo',
    mileage: 'Millaje',
    operationalStatus: 'Estado Operativo',
    active: 'Activo',
    maintenance: 'En Mantenimiento',
    outOfService: 'Fuera de Servicio',
    add: 'Agregar',
    cancel: 'Cancelar',
    description: 'Descripción',
    locationOfDamage: 'Ubicación del Daño',
    severity: 'Severidad',
    status: 'Estado',
    notes: 'Notas',
    driverName: 'Nombre del Conductor',
    driverNamePlaceholder: 'Ingrese el nombre del conductor',
    driverAtFault: '¿Tuvo la Culpa?',
    yes: 'Sí',
    no: 'No',
    photos: 'Fotos',
    dropPhotos: 'Arrastra y suelta fotos aquí',
    clickToSelect: 'o haz clic para seleccionar',
    submit: 'Enviar',
    reported: 'Reportado',
    inProgress: 'En Progreso',
    repaired: 'Reparado',
    low: 'Bajo',
    medium: 'Medio',
    high: 'Alto',
    critical: 'Crítico',
    noVans: 'No hay vans en la flota',
    noDamages: 'No hay reportes de daños',
    viewDamages: 'Ver Daños',
    removeVan: 'Eliminar',
    selectVan: 'Seleccionar Van',
    selectVanPlaceholder: 'Elige una van',
    damageDescription: 'Descripción del Daño',
    descriptionPlaceholder: 'Describe el daño en detalle',
    damageLocation: 'Ubicación del Daño',
    locationPlaceholder: 'Ej: Puerta trasera izquierda',
    selectSeverity: 'Seleccionar Severidad',
    selectStatus: 'Seleccionar Estado',
    uploadPhotos: 'Subir Fotos',
    dragAndDrop: 'Arrastra y suelta fotos aquí o haz clic para seleccionar',
    additionalNotes: 'Notas Adicionales',
    notesPlaceholder: 'Cualquier información adicional',
    submitReport: 'Enviar Reporte',
    damageHistory: 'Historial de Daños',
    plateNumber: 'Placa',
    model: 'Modelo',
    year: 'Año',
    addNewVan: 'Agregar Nueva Van',
    plateNumberInput: 'Número de Placa',
    plateNumberPlaceholder: 'Ej: AMZ-1234',
    modelInput: 'Modelo',
    modelPlaceholder: 'Ej: Mercedes Sprinter',
    yearInput: 'Año',
    mileageInput: 'Millaje',
    vanStatus: 'Estado de la Van',
    addVanButton: 'Agregar Van',
    connectGoogleSheets: 'Conectar Google Sheets',
    spreadsheetId: 'ID de la Hoja de Cálculo',
    spreadsheetIdPlaceholder: 'Ingrese el ID de Google Sheets',
    connect: 'Conectar',
    disconnect: 'Desconectar',
    connected: 'Conectado',
    notConnected: 'No Conectado',
    saveToSheet: 'Guardar en Sheet',
    syncData: 'Sincronizar Datos',
    daysGrounded: 'Días Fuera de Servicio',
    paveDueBy: 'Pave Due By',
    lastPave: 'Last Pave',
    pendingMaintenance: 'Mantenimiento Pendiente',
    dateSentForRepair: 'Fecha Enviado a Reparar',
    locationOfVan: 'Ubicación de la Van',
    estimateDateForRepair: 'Fecha Estimada de Reparación',
    issues: 'Issues',
    dateReported: 'Fecha Reportado',
    close: 'Cerrar',
    searchPlaceholder: 'Buscar van por número, placa o VIN...',
    gridView: 'Vista Cuadrícula',
    listView: 'Vista Lista'
  },
  en: {
    appTitle: 'Amazon Fleet Damage Tracker',
    fleet: 'Fleet',
    damages: 'Damages',
    totalVans: 'Total Vans',
    activeDamages: 'Active Damages',
    addVan: 'Add Van',
    reportDamage: 'Report Damage',
    vanNumber: 'Van Number',
    vanType: 'Van Type',
    vin: 'VIN',
    plate: 'Plate',
    registrationExp: 'Registration Exp.',
    assetStatus: 'Asset Status',
    mileage: 'Mileage',
    operationalStatus: 'Operational Status',
    active: 'Active',
    maintenance: 'Maintenance',
    outOfService: 'Out of Service',
    add: 'Add',
    cancel: 'Cancel',
    description: 'Description',
    locationOfDamage: 'Location of Damage',
    severity: 'Severity',
    status: 'Status',
    notes: 'Notes',
    driverName: 'Driver Name',
    driverNamePlaceholder: 'Enter driver name',
    driverAtFault: 'Driver at Fault?',
    yes: 'Yes',
    no: 'No',
    photos: 'Photos',
    dropPhotos: 'Drop photos here',
    clickToSelect: 'or click to select',
    submit: 'Submit',
    reported: 'Reported',
    inProgress: 'In Progress',
    repaired: 'Repaired',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    noVans: 'No vans in fleet',
    noDamages: 'No damage reports',
    viewDamages: 'View Damages',
    removeVan: 'Remove',
    selectVan: 'Select Van',
    selectVanPlaceholder: 'Choose a van',
    damageDescription: 'Damage Description',
    descriptionPlaceholder: 'Describe the damage in detail',
    damageLocation: 'Damage Location',
    locationPlaceholder: 'E.g: Rear left door',
    selectSeverity: 'Select Severity',
    selectStatus: 'Select Status',
    uploadPhotos: 'Upload Photos',
    dragAndDrop: 'Drag and drop photos here or click to select',
    additionalNotes: 'Additional Notes',
    notesPlaceholder: 'Any additional information',
    submitReport: 'Submit Report',
    damageHistory: 'Damage History',
    plateNumber: 'Plate',
    model: 'Model',
    year: 'Year',
    addNewVan: 'Add New Van',
    plateNumberInput: 'Plate Number',
    plateNumberPlaceholder: 'E.g: AMZ-1234',
    modelInput: 'Model',
    modelPlaceholder: 'E.g: Mercedes Sprinter',
    yearInput: 'Year',
    mileageInput: 'Mileage',
    vanStatus: 'Van Status',
    addVanButton: 'Add Van',
    connectGoogleSheets: 'Connect Google Sheets',
    spreadsheetId: 'Spreadsheet ID',
    spreadsheetIdPlaceholder: 'Enter Google Sheets ID',
    connect: 'Connect',
    disconnect: 'Disconnect',
    connected: 'Connected',
    notConnected: 'Not Connected',
    saveToSheet: 'Save to Sheet',
    syncData: 'Sync Data',
    daysGrounded: 'Days Grounded',
    paveDueBy: 'Pave Due By',
    lastPave: 'Last Pave',
    pendingMaintenance: 'Pending Maintenance',
    dateSentForRepair: 'Date Sent for Repair',
    locationOfVan: 'Location of Van',
    estimateDateForRepair: 'Estimate Date for Repair',
    issues: 'Issues',
    dateReported: 'Date Reported',
    close: 'Close',
    searchPlaceholder: 'Search van by number, plate or VIN...',
    gridView: 'Grid View',
    listView: 'List View'
  }
};
